import time
import random
key='Y'
print("%76s"%("*"*32))
sleep=time.sleep(1)
print("%76s"%("**  WELCOME TO THE DICE GAME  **"))
sleep=time.sleep(1)
print("%76s" %("*" *32))
sleep=time.sleep(1)
print("Try out your luck!!")
sleep=time.sleep(1)
print("Select a number between 1-6 and lets see in how many trial you will guess the correct number")
sleep=time.sleep(1)
while(key=='Y'):
    num=int(input("Enter a number of your choice (1-6): "))
    print("\nROLLING",end="")
    for n in range(1,7):
        x=time.sleep(0.5)
        print("." ,end="")
    y=random.randint(1,6)
    print('\n\nNumber generated by dice is %d'%(y))
    if(y==num):
        print("%73s \n %72s \n %72s" % ("*" * 23, "**  CONGRATULATIONS  **", "*" * 23))
        print("%77s \n %76s \n %76s" % ("*" * 32, "**   YOU ARE A GOOD GUESSER   **", "*" * 32))
    else:
        print("Sorry !")
        print("Better Luck Next Time..")
    key=str(input("Wanna try your Luck Again (Y/N) : "))
else:
    print("Thank You For Playing")